# Build a go artifact
# - use a VM container image capabilities
name: Build

on:
  push:
    branches: 
      - dev
      - main
    tags:
      - '*'  # Trigger on any new tag

jobs:
  run-inside-vm:
    runs-on: ubuntu-latest # denote a VM
    steps:
      - name: display host config
        run: cat /proc/1/cgroup

      - name: display os config
        run: cat /etc/os-release

  build-inside-container:
    runs-on: ubuntu-latest  # denote a VM
    container:              # denote a VM container
      image: golang:1.24
    env:
      ARTIFACT_BASE_NAME: luc  # define variable here
    steps:
      - name: show host config
        run: cat /proc/1/cgroup

      - name: show os config
        run: cat /etc/os-release

      - name: Check Go version
        run: go version

      - name: Define GOOS AND GOARCH envars
        id: githubenv
        run: |
          echo "GOOS=$(go env GOOS)"     >> $GITHUB_OUTPUT
          echo "GOARCH=$(go env GOARCH)" >> $GITHUB_OUTPUT

      - name: Checkout git repo     # clone current git repository
        uses: actions/checkout@v4   # https://github.com/actions/checkout

      - name: check current folder
        run: pwd ; ls -la

      - name: Build the artifact 
        run: go build -v -buildvcs=false -o ${{ env.ARTIFACT_BASE_NAME }} # workaround since go 1.18+

      - name: check binary is built
        run: ls -lh ${{ env.ARTIFACT_BASE_NAME }}

      - name: Upload artifact             # in artifact section of the workflow instance
        uses: actions/upload-artifact@v4  # https://github.com/actions/upload-artifact
        with:
          name: ${{ env.ARTIFACT_BASE_NAME }}-${{ steps.githubenv.outputs.GOOS }}-${{ steps.githubenv.outputs.GOARCH }}  # e.g. "luc-linux-arm64"   
          path: ${{ env.ARTIFACT_BASE_NAME }} # the src artifact

  build-other-artifact:
    runs-on: ubuntu-latest  # denote a VM
    env:
      ARTIFACT_BASE_NAME: luc  # define variable here
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [arm64]
    steps:
      - name: Checkout git repo     # clone current git repository
        uses: actions/checkout@v4   # https://github.com/actions/checkout

      - name: Build
        env:
          ARTIFACT_NAME: ${{ env.ARTIFACT_BASE_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ${{ env.ARTIFACT_NAME }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}