# Build a go artifact
name: Build

on:
  push:
    branches: 
      - dev
      - main
    tags:
      - '*'  # Trigger on any new tag

jobs:
  run-in-vm:
    runs-on: ubuntu-latest # denote a VM
    steps:
      - name: display host config
        run: cat /proc/1/cgroup

      - name: display os config
        run: cat /etc/os-release

  build-in-container:
    runs-on: ubuntu-latest  # denote a VM
    container:              # denote a VM container
      image: golang:1.24
    env:
      ARTIFACT_NAME: luc  # define variable here
    steps:
      - name: show host config
        run: cat /proc/1/cgroup

      - name: show os config
        run: cat /etc/os-release

      - name: Check Go version
        run: go version

      - name: Checkout code         # clone current git repository
        uses: actions/checkout@v4   # https://github.com/actions/checkout

      - name: check current folder
        run: pwd ; ls -la

      - name: Build the artifact 
        run: go build -v -buildvcs=false -o $ARTIFACT_NAME # workaround since go 1.18+

      - name: check binary is built
        run: ls -lh $ARTIFACT_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
        with:
          name: ${{ env.ARTIFACT_NAME }}-binary-${{ github.run_number }}   # the new name
          path: ${{ env.ARTIFACT_NAME }}                                   # the artifact just build
