# release a go artifact
# - use a VM image capabilities, no container
name: Release

on:
  workflow_run: # This workflow is triggered when the workflow completes (success or failure). 
    workflows:
      - Tag   # the name of the workflow (inside the yaml)
    types:
      - completed

jobs:
  create-release-from-tag:
    env:
      TAG_FILEPATH: "./.github/tag.auto.txt"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest     # the VM
    steps:
      - name: checkout the current git repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }} # get the branch that was tagged

      - name: get the tag name # and put it in the github env
        run: |
          TAG_NAME=$(cat "${{ env.TAG_FILEPATH }}" | tail -n 1)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create The Release with tag ${{ env.TAG_NAME }}
        uses: softprops/action-gh-release@v1  # https://github.com/softprops/action-gh-release
        with:
          tag_name: ${{ env.TAG_NAME }}    # tag that triggered the workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: summary     # allow identification in github UI
        run: |
          echo "Branch:   ${{ github.event.workflow_run.head_branch }}"
          echo "Commit:   ${{ github.event.workflow_run.head_sha }}"
          echo "Tag filepath: ${{ env.TAG_FILEPATH }}"
          echo "Tag name:     ${{ env.TAG_NAME }}"
