# create a release after artifact are built
name: Release

on:
  workflow_run: # This workflow is triggered when the workflow completes (success or failure). 
    workflows:
      - Build   # the name of the workflow (inside the yaml)
    types:
      - completed

jobs:
  create-release-after-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # build is on success
    env:
      TAG_FILEPATH: "./.github/tag.auto.txt"
    runs-on: ubuntu-latest     # the VM
    steps:    

      - name: checkout the current git repo # with tags in it
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history (required for tags)
          fetch-tags: true  # Explicit fetch tags

      - name: Get the latest TAG # that normally triggered this workflow
        id: get_tag
        run: |
          echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: show latest tag - ${{ steps.get_tag.outputs.TAG_NAME }}
        run: echo

      - name: Get the workflow ID that trigger this workflow (instance)
        id: get_wf_id
        env:
          WORKFLOW_ID_01: ${{ github.event.workflow_run.workflow_id }}
          WORKFLOW_ID_02: ${{ github.event.workflow_run.id }}
        run: echo "WORKFLOW_ID=${WORKFLOW_ID}" >> $GITHUB_OUTPUT

      - name: show caller workflow id - ${{ steps.get_wf_id.outputs.WORKFLOW_ID_01 }} - ${{ steps.get_wf_id.outputs.WORKFLOW_ID_02 }}
        run: echo

      - name: List artifacts to attach to this release
        run: gh --version

# after
# Use GitHub API to download artifact  
#    gh run download $RUN_ID --artifact=my-data  
#  env:  
#    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  