# release a go artifact
name: Release

on:
  push:
    tags:
      - '*'  # on any new pushed tag (new or force-pushed).

jobs:
  create-release:
    runs-on: ubuntu-latest     # the VM
    env:
      TAG_NAME: ${{ github.ref_name }}   # Tag that triggered the workflow
    steps:
      - name: Create release for tag ${{ env.TAG_NAME }}    
        run: |
          echo "Tag that triggered and used for this release : ${{ env.TAG_NAME }}"
      - name: Create The Release
        uses: softprops/action-gh-release@v1  # https://github.com/softprops/action-gh-release
        with:
          tag_name: ${{ env.TAG_NAME }}    # tag that triggered the workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
