# create a release after artifact are built
name: Release

on:
  workflow_run: # This workflow is triggered when the workflow completes (success or failure). 
    workflows:
      - Build   # the name of the workflow (inside the yaml)
    types:
      - completed

jobs:
  create-release-after-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # build is on success
    env:
      TAG_FILEPATH: "./.github/tag.auto.txt"
    runs-on: ubuntu-latest     # the VM
    steps:    

      - name: checkout the current git repo # with tags in it
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history (required for tags)
          fetch-tags: true  # Explicit fetch tags

      - name: Get the latest TAG # that normally triggered this workflow
        id: get_tag
        run: |
          echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: show latest tag - ${{ steps.get_tag.outputs.TAG_NAME }}
        run: echo

      - name: Get the workflow (instance) info that trigger this workflow (instance)
        id: get_wf_instance_info
        env:
          WORKFLOW_ID: ${{ github.event.workflow_run.workflow_id }}
          WORKFLOW_INSTANCE_ID: ${{ github.event.workflow_run.id }}
        run: echo

      - name: List artifacts to attach to this release 01
        env:
            GH_TOKEN: ${{ github.token }}      
        run: gh run list

      - name: List artifacts to attach to this release 02
        env:
            GH_TOKEN: ${{ github.token }}      
        run: gh run view




# run: gh run view ${{ github.run_id }} --json artifacts --jq '.artifacts[].name'
# run: gh run artifacts --run-id ${{ steps.get_wf_instance_info.outputs.WORKFLOW_INSTANCE_ID }}


