# create a release after artifact are built
name: Release

on:
  workflow_run: # This workflow is triggered when the workflow completes (success or failure). 
    workflows:
      - Build   # the name of the workflow (inside the yaml)
    types:
      - completed

jobs:
  create-release-after-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # build is on success
    env:
      TAG_FILEPATH: "./.github/tag.auto.txt"
    runs-on: ubuntu-latest     # the VM
    steps:    
      - name: checkout the current git repo
        uses: actions/checkout@v4

      - name: Get latest tag
        id: gettag
        run: |
          run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: show latest tag - ${{ steps.gettag.outputs.TAG }}
        run: echo