# Add a TAG to a repository
# - use a VM image capabilities, no container
name: Tag

on:
  push:
    branches: 
      - dev
      - main

jobs:
  create-tag-inside-vm:
    runs-on: ubuntu-latest
    env:                          # variables shared by all steps
      BRANCH_NAME:  ${{ github.ref_name }}
      RUN_NUMBER:   ${{ github.event.workflow_run.run_number }}
      TAG_FILEPATH: "./.github/tag.auto.txt"  # a repo folder
      VERSION     : "v0.0.1"
    
    steps:
      - name: checkout the current git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # fetch full git history - mandatory when using some git commands like `git tag`

      - name: configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"


      - name: create and push the TAG  ${{ env.TAG_NAME }} # no fails if tag already exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME:     ${{ env.VERSION }}-${{ env.BRANCH_NAME }}
        run: |
          echo "will create and push the tag : ${{ env.TAG_NAME }}"
          git tag -f "${{ env.TAG_NAME }}" || { echo "Tagging failed"; exit 1; }
          git push --force origin "${{ env.TAG_NAME }}"  || { echo "Tag push failed"; exit 2; }
          echo "Tag $TAG_NAME pushed successfully"

      - name: Display commit after tagging - ${{ github.sha }}
        run: |
          echo "Associated tags:"
          git tag --points-at HEAD