# Build a repository TAG
name: Tag

on:
  workflow_run: # This workflow is triggered when the workflow completes (success or failure). 
    workflows:
      - Build   # the name of the workflow (inside the yaml)
    types:
      - completed

jobs:
  create-tag-on-vm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:                    # variables shared by all steps
      VERSION: v0.0.1       # You can update this manually or generate dynamically later
      BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
      RUN_NUMBER:   ${{ github.event.workflow_run.run_number }}
      # TAG_NAME: ${{ format('{0}-{1}', env.VERSION, env.BRANCH_NAME) }}    
      

    steps:
      - name: Checkout the current git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # fetch full git history, all tags and branches - mandatory when you use some git commands like `git tag`

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Define var TAG_NAME and put it in the github env
        id: tagname
        # run: echo "TAG_NAME=${VERSION}-${BRANCH_NAME}-${RUN_NUMBER}" >> $GITHUB_ENV
        run: echo "TAG_NAME=${VERSION}-${BRANCH_NAME}" >> $GITHUB_ENV

      # - name: Create the tag ${{ env.TAG_NAME }} # fails if tag already exists
      #   run: |
      #     git tag "${{ env.TAG_NAME }}"

      # - name: Push the tag ${{ env.TAG_NAME }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git push origin "${{ env.TAG_NAME }}"


      - name: Create/update a tag ${{ env.TAG_NAME }} # no tails if tag already exists
        run: |
          git tag -f "${{ env.TAG_NAME }}"


      - name: Push the tag ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force origin "${{ env.TAG_NAME }}"

      - name: summary     # allow identification in github UI
        run: |
          echo "Branch:   ${{ github.event.workflow_run.head_branch }}"
          echo "Commit:   ${{ github.event.workflow_run.head_sha }}"
          echo "Tag name: ${{ env.TAG_NAME }}"
